after_success:
- if [[ $TRAVIS_TAG =~ ^v.*$ ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then chmod +x ./.github/website.sh; .github/website.sh; fi
before_cache:
- rm -rf $HOME/.m2/repository/org/joda/time
- find $TRAVIS_BUILD_DIR -name '*.clz' -print | cpio -pvdumB $HOME/ekstazi_cache
before_script:
- (cd $HOME/ekstazi_cache && find . -name '*.clz' -print | cpio -pvdumB /)
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/ekstazi_cache
env:
  global:
    secure: UK9A4eHPOP6XkYbST1kpv3gVEZTBqp79eCF0nqpXejbXihY58MNVZ0aGt8IM/ZThO/UoK+AxWjaSLljE2Neo4ehxvRHsRG0bIhAoCBUjP6f6vuMYTZlRNb9W+NM3RjXvrQGnCM3PTckWaFQ6i5Ny4e1GuETSdh96Yk7WNn6DMJM=
install:
- mvn --version
jdk:
- oraclejdk8
- openjdk7
language: java
script:
- mvn install site -e -B
sudo: false
